apiVersion: ENC[AES256_GCM,data:fKw=,iv:1GQldaQdylsfvZ+KVFhzmq5tp1a2HtPya1jSZ9N+jpQ=,tag:R0egD59oQ1jcR4f6u9EUDQ==,type:str]
kind: ENC[AES256_GCM,data:k9GwcREX,iv:klU8z8HINzWShCIK8VchHoT9PiqoANqjMHG0K0bpgo8=,tag:0Ev59cvzHLmUhbUIWZgjlg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GvV2QPT7MhpTB1M=,iv:ETBiXTdfYx+TD8MJ8N1BAtBGtpnXQO6M5+DyLUlj4Io=,tag:txrFdw3MSC6T6Lfvsocaeg==,type:str]
    namespace: ENC[AES256_GCM,data:2X5p7A78cg==,iv:uH2LDM8YacxxJn0XJ3AtvKkerb2k7GSIDr+CarzCBzs=,tag:rOVuv7rcXCD3pQixuhAPpw==,type:str]
type: ENC[AES256_GCM,data:S3xreJLM,iv:NpaBzPvcLOi+RymViAweJpOw6Ty5IjZ3YNtRtE7MDhA=,tag:768yD+Mqd7aVAeQvZZrlKQ==,type:str]
stringData:
    username: ENC[AES256_GCM,data:Yu1z7+s=,iv:LhaE8o0B8IQWaHR4haO1QocvWo3xhmyw7uHh3fR4/iM=,tag:YqTCoFMgR27UObh1Wi0f+g==,type:str]
    password: ENC[AES256_GCM,data:rwrKfuGA3eUQbAsdoQ==,iv:jLJO2/n9IggDS2shVg+BqZB+WDHHQH0ldcHYAxrEtRA=,tag:xZXBNyZ9iCfFHmDxK4L8tA==,type:str]
sops:
    age:
        - recipient: age1hxxlargr6y5esw8n76kjv7h0ap7cmf282n6ltncvrs2yv7dpsadqn39hk6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRDkvNXJLbUd5L0xJWVIx
            SXFHUmxPMkNsTGhmZXdmVVl5YStSK25sOUE0CngwRzh2Z0hXcDRFNUVJK2E5c0s2
            VDhRMENiMnlVWHJ2MW1DUk05dXpQTHMKLS0tIEE2MXhQMVphdFlPNUVYZWFUdXFa
            bGtya0taRyt5c3ZkSjBJU09oTGhCRGMK0W3bSuXt0OzEjGWKIUG0rdE+7XLkn9zN
            00ag3jPRwoP+jUdSfXp8hOeEBhPkqTXfo0weBvV+NI3ihDXdmLLTkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T07:18:41Z"
    mac: ENC[AES256_GCM,data:4kiCrQUVfoBnJqAfmdDJ44AETC0Nss2qicFhve5BLaM1AvfEj0bYuSxNI4W14Ch4mkyFTl9x9nk5qKha0/aWGNicBMb3gA8tE92dL+N1UvMKuv+uOlaJ1tuLpeT63CW0WUqyg3CLHJ8Jq7uU5TcKH7garni5cEZ253jt/3TfmTE=,iv:DZFHr9wdwwbzC7zQ6ap3FufTAdKdAgd8nAX/wELkFjA=,tag:/J9e++nmgvxaGE10JFhQPw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
