apiVersion: v1
kind: Secret
metadata:
    name: demo-secret
    namespace: default
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Kkdftoc=,iv:Tot2V9rvggZsn2yKk9sFJNTZ58ltcB8NoH+VlshkPN8=,tag:ETDUk914jMeuQm3ah2jLiA==,type:str]
    password: ENC[AES256_GCM,data:3LIDW4JDgOJyMJ7UHQ==,iv:mDh5LO0+OhEPT4ehOHGjwdI71MnLhcqkbdwpgmEKoIE=,tag:XcnnhA/I++MWeY435XwbUQ==,type:str]
sops:
    age:
        - recipient: age1hxxlargr6y5esw8n76kjv7h0ap7cmf282n6ltncvrs2yv7dpsadqn39hk6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4blBhTXp2U2VmK0VscUlP
            bUpxMlNucXZZLzVOTW1kUGpCYy9wdGY1T0JBClBFZmVzNzhqMFU2VXFoUFhpaFBI
            VlJtZkQvRGJ1VDhteVZTZkhnNVI3bHcKLS0tIHB0Z3l1Qi8rNFZTd1ZTMGkzcmhL
            Zkk2cG94SlZJd0RDQ3c3NCtnVkhJNEUK6dgx0shrrqtXlrPsTmrrR9mGdc4/V9pj
            T1y0eODspWWmupqOHPdqentCA4Uvg9U9XsgQztXkzgiNlYBOH+zO1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-12T12:41:48Z"
    mac: ENC[AES256_GCM,data:2QoY15dYEpcjK/ZAlroEsCuTQ1pIqf/PrqP/f+DS7mfVZivZy6G0UkD+Vhltgjis7LvkLF+Q7ddFfSYGH+JRDP5jT6l0eSM4YaWLwv2Gqf7T/GGB/gTMNhW7SQHHalu1tjGJJbPfbAl+MPxqTDoa/+FOOI1SFN/P7xS6UfN9vs4=,iv:V164nE6eEz7AKn00FnWdRguMo5F0EPJ74vFhATjVcos=,tag:eMx7S5uY+tymm7VFDxpiTw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
