apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: demo-sops-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/YOUR_USERNAME/gitops.git
    targetRevision: HEAD
    path: apps/demo-sops-app

    kustomize:
      buildOptions: "--enable-alpha-plugins --enable-exec"

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
